// AUTOGENERATED FILE

#if defined(__x86_64__) || 0
#define GOARCH "amd64"
#define SYZ_REVISION "dce9e49ca9186930b58482f3dda37026ade77a8c"
#define SYZ_PAGE_SIZE 4096
#define SYZ_NUM_PAGES 4096
#define SYZ_DATA_OFFSET 536870912
unsigned syscall_count = 20;
struct call_t syscalls[] = {
    {"SYS_brk", 19},
    {"SYS_event_send", 48},
    {"SYS_exec", 4},
    {"SYS_getpid", 18},
    {"SYS_gettime", 17},
    {"SYS_mbox_free", 53},
    {"SYS_mbox_info", 54},
    {"SYS_mbox_init", 50},
    {"SYS_mbox_send", 51},
    {"SYS_mmap", 20},
    {"SYS_open", 100},
    {"SYS_pgdir", 31},
    {"SYS_putc", 30},
    {"SYS_sem_free", 43},
    {"SYS_sem_get_value", 44},
    {"SYS_sem_init", 40},
    {"SYS_sem_post", 41},
    {"SYS_shmem", 22},
    {"SYS_wait", 3},
    {"SYS_yield", 10},

};
#endif
